services:

  api:
    build: .
    container_name: controle_insumos_api
    restart: always

    ports:
      - "127.0.0.1:3000:3000"

    env_file:
      - .env

    networks:
      - rede_api

    deploy:
      resources:
        limits:
          memory: 256M


networks:
  rede_api:
    external: true